#!/bin/bash -e

if [ -f "/run/initramfs/ram/root.sfs" ]; then
	ROOTSFS="/run/initramfs/ram/root.sfs"
elif [ -f "/run/initramfs/medium/kael/root.sfs" ]; then
	ROOTSFS="/run/initramfs/medium/kael/root.sfs"
else
	echo "squashed image not found!"
	exit 1
fi

INSTALLDIR=/mnt

read -p "Enter root partition: " rootpart
read -p "Enter hostname: " hostname
read -p "Enter username: " username
read -s -p "Enter user password: " userpswd
echo
read -s -p "Enter root password: " rootpswd
echo
read -p "Enter grub drive: " grubdrive

mkfs.ext4 -F -L KaelLinux $rootpart
mount $rootpart $INSTALLDIR
unsquashfs -f -i -d $INSTALLDIR $ROOTSFS
echo "# <device> <dir> <type> <options> <dump> <fsck>" > $INSTALLDIR/etc/fstab
echo "UUID=$(blkid -o value -s UUID "$rootpart") / ext4 defaults 1 1" >> $INSTALLDIR/etc/fstab
useradd -R $INSTALLDIR -m -G users,wheel,audio,video -s /bin/bash $username
echo "$username:$userpswd" | chpasswd -R $INSTALLDIR -c SHA512
echo "root:$rootpswd" | chpasswd -R $INSTALLDIR -c SHA512
xchroot $INSTALLDIR mkinitramfs
xchroot $INSTALLDIR grub-install $grubdrive
xchroot $INSTALLDIR grub-mkconfig -o /boot/grub/grub.cfg

umount $INSTALLDIR
