#!/bin/bash

printhelp() {
	cat << EOF

Usage:
  $(basename $0) <newroot> <command>
  
(omit command to chroot only)
  
EOF
}

msgerr() {
	echo -e "ERROR: $@"
}
	
if [ "$UID" != "0" ]; then
	msgerr "$(basename $0) need root access!"
	printhelp
	exit 1
fi

TARGET=$1

if [ -z $1 ]; then
	msgerr "Please set directory for chroot!"
	printhelp
	exit 1
fi

if [ ! -d $TARGET ]; then
	msgerr "Directory '$TARGET' not exist"
	printhelp
	exit 1
fi

shift

CMD=$@
if [ -z $2 ]; then
	CMD="/bin/bash --login"
fi

if [ -e /sys/firmware/efi/systab ]; then
	EFI_SYSTEM=1
fi

pushd $TARGET &>/dev/null

mount --bind /dev $TARGET/dev
mount -t devpts devpts $TARGET/dev/pts -o gid=5,mode=620
mount -t proc proc $TARGET/proc
mount -t sysfs sysfs $TARGET/sys
if [ -n "$EFI_SYSTEM" ]; then
	mount --bind /sys/firmware/efi/efivars $TARGET/sys/firmware/efi/efivars
fi
mount -t tmpfs tmpfs $TARGET/run

if [ -h $TARGET/dev/shm ]; then
  mkdir -p $TARGET/$(readlink $TARGET/dev/shm)
fi

cp -L /etc/resolv.conf $TARGET/etc

chroot "$TARGET" /usr/bin/env -i \
HOME=/root \
TERM="$TERM" \
PS1='\u:\w\$ ' \
PATH=/bin:/usr/bin:/sbin:/usr/sbin $CMD

retval=$?

popd &>/dev/null

umount $TARGET/dev/pts
umount $TARGET/dev
umount $TARGET/run
umount $TARGET/proc
if [ -n "$EFI_SYSTEM" ]; then
	umount $TARGET/sys/firmware/efi/efivars
fi
umount $TARGET/sys

exit $retval
