#!/bin/bash

msg() {
	echo "=> $*"
}

msg2() {
	echo "-> $*"
}

msgerr() {
	echo "!> $*"
}

fetch() {
	filename=$(basename $1)
	url=$1
	wgetcmd="wget --passive-ftp --tries=3 --waitretry=3 --output-document=$SRCDIR/$filename.part"
	
	if [ ! -f $SRCDIR/$filename ]; then
		[[ -f $SRCDIR/$filename.part ]] && resume="-c"
		$wgetcmd $resume $url && \
			mv $SRCDIR/$filename.part $SRCDIR/$filename
	fi
}

unpack() {
	rm -fr "$BUILDDIR/$name"
	mkdir -p "$BUILDDIR/$name"
	for src in $source; do
		filename=$(basename $src)
		case $src in
			*.tar|*.tar.gz|*.tar.Z|*.tgz|*.tar.bz2|*.tbz2|*.tar.xz|*.txz|*.tar.lzma|*.zip)
				msg "extracting $filename..."
				tar -xf "$SRCDIR/$filename" -C "$BUILDDIR/$name" || {
					msgerr "failed extracting $filename"
					exit 1
				};;
		esac
	done
}

ports() {
	[ "$1" ] || return 1
	[ -f "$ROOTFS/var/lib/scratchpkg/index/$1/.pkginfo" ] && return 0
	
	mkdir -p $ROOTFS/var/lib/scratchpkg/index
	[ -f "$PORTSDIR/$1/spkgbuild" ] || {
		msgerr "Ports '$1' not exist."
		return 1
	}
	cd $PORTSDIR/$1
	settermtitle "Building '$1'..."
	pkgbuild --config=$PKGBUILDCONF --root=$ROOTFS -i || {
		settermtitle "Building '$1' failed."
		exit 1
	}
	cd - >/dev/null
}

cross_compiler() {
	[ "$1" ] || return 1
	[ -f "$TCDIR/$1" ] && return 0
	
	source $TCSCRIPTDIR/$1
	if [ "$source" ]; then
		for src in $source; do
			fetch $src
		done
	fi

	unpack || {
		msgerr "Failed to unpack '$(basename $source)'."
		return 1
	}
	
	cd "$BUILDDIR/$name"

	if [ "$(type -t build)" = "function" ]; then
		settermtitle "Building '$1'..."
		(set -e -x; build 2>&1)
		if [ "$?" != 0 ]; then
			settermtitle "Building '$1' failed"
			msgerr "'build' failed"
			exit 1
		else
			settermtitle "Building '$1' completed"
			msg "Cross toolchain build for '$name-$version' completed."
			touch "$TCDIR/$1"
			rm -fr "$BUILDDIR/$name"
		fi
	fi
	
	cd - >/dev/null
}

settermtitle() {
	echo -en "\033]0;$*\a"
}

setup_pkgbuildconf() {
	cat << EOF > pkgbuild.conf
export HOST="$HOST"
export TARGET="$TARGET"
export CARCH="$CARCH"

export CC="$TARGET-gcc"
export CXX="$TARGET-g++"
export AR="$TARGET-ar"
export AS="$TARGET-as"
export RANLIB="$TARGET-ranlib"
export LD="$TARGET-ld"
export STRIP="$TARGET-strip"

export TCDIR="$TCDIR"
export PATH=$PATH

export ROOTFS="$ROOTFS"

export PKG_CONFIG_PATH="$ROOTFS/usr/lib/pkgconfig:$ROOTFS/usr/share/pkgconfig"
export PKG_CONFIG_SYSROOT_DIR="$ROOTFS"

BOOTSTRAP=1

MAKEFLAGS="$MAKEFLAGS"
CFLAGS="$CFLAGS"
CXXFLAGS="$CXXFLAGS"

SOURCE_DIR="$SRCDIR"
PACKAGE_DIR="$PKGDIR"
WORK_DIR="$BUILDDIR"
EOF
}

build_livecd() {
	[ "$LIVE" = 1 ] || return 0
	msg "Building liveiso..."
	make_liveworkdir
	make_initramfs
	make_squashfs
	make_efiboot
	make_iso
	cleaning
}

build_base() {
	mkdir -p "$ROOTFS" "$BUILDDIR" "$SRCDIR" "$PKGDIR" "$TCDIR"
	
	setup_pkgbuildconf

	msg "Building base packages..."
	for b in $cross_toolchain $base_system $extra; do
		case $b in
			cross-*) cross_compiler $b || exit $?;;
				  *) ports $b || exit $?;;
		esac
	done

	# copy ports to rootfs
	msg "Copying ports..."
	rm -fr $ROOTFS/usr/ports/core
	mkdir -p $ROOTFS/usr/ports/core
	cp -R ports/* $ROOTFS/usr/ports/core
	rm -f $ROOTFS/usr/ports/core/{REPO,.httpup-repgen-ignore}
	rm -f $ROOTFS/usr/ports/core/*/update

	msg "Running xrevdep..."
	xchroot $ROOTFS xrevdep
}

chroot_run() {
	xchroot $ROOTFS $@
}

make_efiboot() {
	msg "Setup efiboot..."
	
	mkdir -p "$LIVEWDIR"/boot/{grub/{fonts,x86_64-efi},EFI}
	
	if [ -f /usr/share/grub/unicode.pf2 ];then
		cp /usr/share/grub/unicode.pf2 "$LIVEWDIR"/boot/grub/fonts
	fi
	if [ -f "$FILESDIR"/isolinux/splash.png ]; then
		cp "$FILESDIR"/isolinux/splash.png "$LIVEWDIR"/boot/grub/
	fi
	
	echo "set prefix=/boot/grub" > "$LIVEWDIR"/boot/grub-early.cfg
	cp -a /usr/lib/grub/x86_64-efi/*.{mod,lst} "$LIVEWDIR"/boot/grub/x86_64-efi
	cp "$FILESDIR"/grub.cfg "$LIVEWDIR"/boot/grub/

	grub-mkimage \
		-c "$LIVEWDIR"/boot/grub-early.cfg \
		-o "$LIVEWDIR"/boot/EFI/bootx64.efi \
		-O x86_64-efi \
		-p "" iso9660 normal search search_fs_file
		
	modprobe loop
	dd if=/dev/zero of="$LIVEWDIR"/boot/efiboot.img count=4096
	mkdosfs -n KAELLIVECD-UEFI "$LIVEWDIR"/boot/efiboot.img
	mkdir -p "$EFIBOOTDIR"
	mount -o loop "$LIVEWDIR"/boot/efiboot.img "$EFIBOOTDIR"
	mkdir -p "$EFIBOOTDIR"/EFI/boot
	cp "$LIVEWDIR"/boot/EFI/bootx64.efi "$EFIBOOTDIR"/EFI/boot
	
	umount "$EFIBOOTDIR"
	rm -fr "$EFIBOOTDIR"
}

make_iso() {	
	msg "Making iso..."
	rm -f $OUTPUT
	xorriso -as mkisofs \
		  -isohybrid-mbr "$FILESDIR"/isohdpfx.bin \
		-c isolinux/boot.cat \
		-b isolinux/isolinux.bin \
		  -no-emul-boot \
		  -boot-load-size 4 \
		  -boot-info-table \
		  -eltorito-alt-boot \
		-e boot/efiboot.img \
		  -no-emul-boot \
		  -isohybrid-gpt-basdat \
		  -volid $ISOLABEL \
		-o $OUTPUT $LIVEWDIR
}

make_squashfs() {
	msg "Squashing filesystem..."
	mksquashfs $ROOTFS "$LIVEWDIR"/kael/root.sfs \
		-b 1048576 -comp zstd \
		-e $ROOTFS/var/cache/scratchpkg/sources/* \
		-e $ROOTFS/var/cache/scratchpkg/packages/* \
		-e $ROOTFS/var/cache/scratchpkg/work/* \
		-e $ROOTFS/tmp/* 2>/dev/null
}

make_initramfs() {
	msg "Preparing initramfs..."
	cp $ROOTFS/boot/vmlinuz-kael "$LIVEWDIR"/boot/vmlinuz
	sed "s/@ISOLABEL@/$ISOLABEL/g" "$FILESDIR"/livecd.hook > $ROOTFS/usr/share/mkinitramfs/hooks/livecd.hook
	kernver=$(file $ROOTFS/boot/vmlinuz-kael | cut -d ' ' -f9)
	chroot_run mkinitramfs -k $kernver -a livecd -o /boot/initrd-kael.img
	mv $ROOTFS/boot/initrd-kael.img "$LIVEWDIR"/boot/initrd
}

make_liveworkdir() {
	isolinux_files="chain.c32 isolinux.bin ldlinux.c32 libutil.c32 reboot.c32 menu.c32 libcom32.c32 poweroff.c32"
	msg "Preparing iso workdir..."
	rm -fr "$LIVEWDIR"
	mkdir -p "$LIVEWDIR"/{kael,isolinux,boot}
	for file in $isolinux_files; do
		cp "$FILESDIR"/$file "$LIVEWDIR"/isolinux
	done

	cp "$FILESDIR"/isolinux.cfg "$LIVEWDIR"/isolinux
	[ -d liverootfs ] && cp -Ra liverootfs "$LIVEWDIR"
}

cleaning() {
	msg "Cleaning workdir..."
	rm -fr "$LIVEWDIR"
}

build_rootfs() {
	[ "$RFS" = 1 ] || return 0
	rm -f "$BUILDROOT"/kaellinux-rootfs.tar.xz
	pushd "$ROOTFS" >/dev/null
		msg "Building rootfs image..."
		tar -cvJpf "$BUILDROOT"/kaellinux-rootfs.tar.xz * 
	popd >/dev/null
}

parse_opts() {
	while [ "$1" ]; do
		case $1 in
			-jobs=*) JOBS=${1#*=};;
			-root=*) ROOTFS=${1#*=};;
			-pkgbuildconf=*) PKGBUILDCONF=${1#*=};;
			-liveiso) LIVE=1;;
			-rootfs) RFS=1;;
		esac
		shift
	done
}

checkroot() {
	[ "$(id -u)" = 0 ] || {
		msg "Need root access!"
		exit 1
	}
}

parse_opts "$@"

BUILDROOT=$(pwd)
TCDIR="$BUILDROOT/toolchain"
SRCDIR="$BUILDROOT/sources"
PKGDIR="$BUILDROOT/packages"
PORTSDIR="$BUILDROOT/ports"
BUILDDIR="$BUILDROOT/work"
ROOTFS="${ROOTFS:-$BUILDROOT/rootfs}"
TCSCRIPTDIR="$BUILDROOT/tcscripts"
PKGBUILDCONF="${PKGBUILDCONF:-$BUILDROOT/pkgbuild.conf}"
JOBS="${JOBS:-$(nproc)}"

# live iso
ISOLABEL="KAELLIVE"
OUTPUT="kaellive.iso"
LIVEWDIR="$BUILDDIR/live"
FILESDIR="$BUILDROOT/files"
EFIBOOTDIR="$BUILDDIR/efiboot"

export PATH="$TCDIR/bin:$PATH"

export CARCH="$(uname -m)"
export TARGET="$CARCH-linux-musl"
export HOST="$(echo ${MACHTYPE} | sed "s/-[^-]*/-cross/")"

export MAKEFLAGS="-j$JOBS"
export CFLAGS="-O2 -march=x86-64 -pipe"
export CXXFLAGS="${CFLAGS}"

cross_toolchain="cross-scratchpkg linux-api-headers cross-binutils cross-gcc-pass1 cross-musl cross-gcc-pass2"
base_system="filesystem man-pages musl tzdata zlib bzip2 xz file ncurses readline m4 bc binutils gmp mpfr libmpc attr acl shadow
	gcc pkgconf libcap sed psmisc iana-etc bison flex grep bash libtool gdbm gperf expat inetutils perl
	autoconf automake kmod gettext libuargp musl-fts elfutils libressl coreutils diffutils gawk findutils groff
	less gzip iproute2 kbd libpipeline make patch man-db tar texinfo vim procps-ng pcre2 util-linux e2fsprogs
	sysklogd eudev dhcpcd libarchive curl httpup scratchpkg runit runit-bootscripts base"
extra="linux-firmware fuse2 grub mkinitramfs linux efivar popt efibootmgr grub-efi gpm links nnn lzo lz4 zstd squashfs-tools"

checkroot
build_base
build_rootfs
build_livecd

exit 0
