#!/bin/bash -e

chroot_run() {
	mount_pseudofs
	cp -L /etc/resolv.conf $ROOTFS/etc/
	chroot $ROOTFS $@
	retval=$?
	umount_pseudofs
	return $retval
}

mount_pseudofs() {
	mount --bind /dev $ROOTFS/dev
	mount -t devpts devpts $ROOTFS/dev/pts -o gid=5,mode=620
	mount -t proc proc $ROOTFS/proc
	mount -t sysfs sysfs $ROOTFS/sys
	mount -t tmpfs tmpfs $ROOTFS/run
}

umount_pseudofs() {
	umount $ROOTFS/dev/pts &>/dev/null
	umount $ROOTFS/dev &>/dev/null
	umount $ROOTFS/run &>/dev/null
	umount $ROOTFS/proc &>/dev/null
	umount $ROOTFS/sys &>/dev/null
}

BUILDROOT=$(pwd)
SRCDIR="$BUILDROOT/sources"
PKGDIR="$BUILDROOT/packages"
BUILDDIR="$BUILDROOT/work"
ROOTFS="${ROOTFS:-$BUILDROOT/rootfs}"
TCSCRIPTDIR="$BUILDROOT/tcscripts"
PKGBUILDCONF="${PKGBUILDCONF:-$BUILDROOT/pkgbuild.conf}"

# live iso
ISOLABEL="KAELLIVE"
OUTPUT="kaellive.iso"
LIVEWDIR="$BUILDDIR/live"
FILESDIR="$BUILDROOT/files"

isolinux_files="chain.c32 isolinux.bin ldlinux.c32 libutil.c32 reboot.c32 menu.c32 libcom32.c32 poweroff.c32"

rm -fr "$LIVEWDIR"
mkdir -p "$LIVEWDIR"/{kael,isolinux,boot}
for file in $isolinux_files; do
	cp "$FILESDIR"/$file "$LIVEWDIR"/isolinux
done

cp "$FILESDIR"/isolinux.cfg "$LIVEWDIR"/isolinux
[ -d liverootfs ] && cp -Ra liverootfs "$LIVEWDIR"

mksquashfs $ROOTFS "$LIVEWDIR"/kael/root.sfs \
		-b 1048576 -comp xz -Xdict-size 100% \
		-e $ROOTFS/var/cache/scratchpkg/sources/* \
		-e $ROOTFS/var/cache/scratchpkg/packages/* \
		-e $ROOTFS/var/cache/scratchpkg/work/* \
		-e $ROOTFS/tmp/* 2>/dev/null

cp $ROOTFS/boot/vmlinuz-kael "$LIVEWDIR"/boot/vmlinuz
sed "s/@ISOLABEL@/$ISOLABEL/g" "$FILESDIR"/livecd.hook > $ROOTFS/usr/share/mkinitramfs/hooks/livecd.hook
kernver=$(file $ROOTFS/boot/vmlinuz-kael | cut -d ' ' -f9)
chroot_run mkinitramfs -k $kernver -a livecd -o /boot/initrd-kael.img
mv $ROOTFS/boot/initrd-kael.img "$LIVEWDIR"/boot/initrd

rm -f $OUTPUT
xorriso -as mkisofs \
    -c isolinux/boot.cat \
    -b isolinux/isolinux.bin \
      -no-emul-boot \
      -boot-load-size 4 \
      -boot-info-table \
      -no-emul-boot \
      -volid $ISOLABEL \
    -o $OUTPUT "$LIVEWDIR" 

rm -fr "$LIVEWDIR"
