#!/bin/sh -e

[ -f kaellinux.img ] || {
	qemu-img create -f qcow2 kaellinux.img 20G
}

exec qemu-system-x86_64 -enable-kvm \
        -cpu host \
        -drive file=kaellinux.img,if=virtio \
        -netdev user,id=vmnic,hostname=Kael \
        -device virtio-net,netdev=vmnic \
        -device virtio-rng-pci \
        -m 2G \
        -smp 2 \
        -monitor stdio \
        -name "KaelLinux VM" \
        -boot d -cdrom kaellive.iso
