#!/bin/sh

for i in /lib/*.so* /usr/lib/*.so* /bin/* /sbin/* /usr/bin/* /usr/sbin/*; do
	case "$(file -bi $i)" in
		*application/x-sharedlib* | *application/x-executable* | *application/x-pie-executable*)
			case "$(file $i)" in
				*executable*statically\ linked*) continue;;
			esac
			ldd $i >/dev/null 2>&1 || pkgquery provide $i$;;
	esac
done
